### ISSUE TITLE
Request inputValue's notify to be set to true

### ISSUE THREAD

**Issue by raghav135** [cheonhyangzhang/paper-typeahead-input#10]
Thanks for this web component. It is really useful and good.

Request you to kindly make the inputValue's notify attribute to true so that other web components can be notified if any changes are there in this component.

**Comment by torsjonas** [comment]
+1

As a workaround you can currently listen to the bind-value-changed event (fired by the underlying paper-input) which has the same effect, like so

``` javascript
<paper-typeahead-input on-bind-value-changed="doSomething">
</paper-typeahead-input>
```

**Comment by cheonhyangzhang** [comment]
Correct. Can't believe I missed this. This is very critical. 

Have implemented and included in latest release, 1.2.3.

**Comment by cheonhyangzhang** [comment]
Hi @raghav135  Have you got a chance to test it if it's working as you expected?

**Comment by raghav135** [comment]
Hey CheonHyanZhang,
Thanks for the super fast fix for both this issue as well as the other issue in debounce (var self = this).
This fix is working as expected. 
Cheers.

**Comment by cheonhyangzhang** [comment]
Okay. Glad to hear. Just want to double check this issue is resolved so that I could close it.  Thanks for raising the issue.
