### ISSUE TITLE
Formatting results from external url

### ISSUE THREAD

**Issue by BartKrol** [cheonhyangzhang/paper-typeahead-input#12]
Hey! 

It would be nice to add a way to format results from remote url. In my case the endpoint is returning a list of json objects, so I need to unpack them first. It could work in a similar way as in ui bootstrap library for Angular https://angular-ui.github.io/bootstrap/#/typeahead.

Cheers!

**Comment by cheonhyangzhang** [comment]
It sounds right. This is similar to issue #4. 
It is on the wish list. It will be implemented in the future.

**Comment by cheonhyangzhang** [comment]
The feature to support list of json objects is implemented at commit 9d30bddc2e554e2040ccd82b3b15d562fedff3f1

It's available in the latest release v1.3.5.

**Comment by cheonhyangzhang** [comment]
Features have been implemented hence closing the issue.
