### ISSUE TITLE
Element does not actually typeahead

### ISSUE THREAD

**Issue by tony19** [cheonhyangzhang/paper-typeahead-input#18]
This element currently only supports autocomplete suggestions and does not actually typeahead.

If I understand the [definition](http://www.ibm.com/developerworks/rational/library/06/1205_kats_rad1/) correctly, a typeahead automatically appends the suggestion to the input as the user types, as seen in [typeahead.js](https://twitter.github.io/typeahead.js/). However, `paper-typeahead-input` only displays a list of suggestions, requiring the user to manually select the suggestion (e.g., with <kbd>TAB</kbd> <kbd>ENTER</kbd>).

**Comment by cheonhyangzhang** [comment]
Are you saying the feature to show the top matched word even before the user fully type all the letters?

E.g. when user searching for US states, typed IL   and the input field should show  ILlinois ? but linois in lighter color and once user type "TAB" in this case, it will auto complete Illinois. 

Am I understanding right?

**Comment by tony19** [comment]
Yes, that's right.

**Comment by cheonhyangzhang** [comment]
Do you have any thoughts how to implement that?

**Comment by cheonhyangzhang** [comment]
User should be able to see typeahead show up in gray text in the inputbox. 
Inspired by [twitter typeahead](https://twitter.github.io/typeahead.js/) the strategy would be adding extra element to show the typeahead. 
The typeahead would only be seen if the user types the starting part of the first item in the suggestions list. e.g al -> Alabama,   typing bama will hit result Alabama but typeahead will not show in this case.

When user types "Tab", typeahead should autocomplete the word, only if the word it not completed.
When the word is completed, typing "Tab" should behave like the default behavior, which is switching element to interact with.

**Comment by cheonhyangzhang** [comment]
Work in Progress of branch [feat/18](https://github.com/cheonhyangzhang/paper-typeahead-input/tree/feat/18)

**Comment by cheonhyangzhang** [comment]
Hi @tony19 

The typeahead feature is implemented now. It's included with the version v1.3.8.

**Comment by tony19** [comment]
Thanks!
