### ISSUE TITLE
on-pt-item-confirmed doesn't send json object of selected item

### ISSUE THREAD

**Issue by e-frank** [cheonhyangzhang/paper-typeahead-input#21]
i think something was changed from a previous version.
before the update, the data of the selected json object was passed to the on-pt-item-confirmed event, now i can't find the object's data anywhere.

**Comment by cheonhyangzhang** [comment]
What data do you mean?   The pt-item-confirmed event is passing the selected item to the event, which is the <paper-item> element.

**Comment by cheonhyangzhang** [comment]
What version does it pass the selected json to the event?

**Comment by e-frank** [comment]
i can't restore my ancient version.
when i am setting up the items list like this:

``` html
    <paper-typeahead-input 
        data-local-candidates="{{locals}}" 
        autocomplete="off"
        display-prop="text"
        input-object="{{input}}"
        searchable-props="text, id"
        remote-url="data.php?q=%QUERY"
        is-candidates-json="true"
        name="mytypeahead" 
        on-pt-item-confirmed="confirmed"></paper-typeahead-input>
```

``` javaScript
// data is not data, but the selected item (as stated in the docs)
scope.confirmed = function(e, data) {
  console.log('confirmed', e, data);
  scope.price = data.price
}
```

the list of items is created from json-objects.
so when an item is selected/confirmed, my event needs to know about the underlying json data for further processing.

**Comment by cheonhyangzhang** [comment]
well first of all, there is no autocomplete and name property supported for paper-typeahead-input yet.

As for your request, you already assign a variable to input-object property. 
When the event pt-item-confirmed is fire, you have a callback function confirmed for that. Inside of it, you will be able to know the selected item by your variable input. 

```
scope.confirmed = function(e) {
  console.log(scope.input);
  scope.price = scope.input.price;
}
```

**Comment by e-frank** [comment]
thanks, you are right, data is in the {{Input}}.
i had to add autocomplete, because it screws up on my surface rt:

``` javascript
      autocomplete:{
        type:String,
        value:"off"
      }
```

``` javaScript
      // input.$.input.autocomplete = 'address-level4';
      input.$.input.autocomplete = this.autocomplete;
```

**Comment by cheonhyangzhang** [comment]
Oh  so about the line input.$.input.autocomplete = 'address-level4'; I think that's added to fix a bug of the chrome autofilling problem. It's a workaround.   About the autocomplete, do you think it's an issue that need to be resolved? What do you mean by "it screws up" surface rt?  What kind of bug it is?
