### ISSUE TITLE
Make _suggestions property public

### ISSUE THREAD

**Issue by nicholaswmin** [cheonhyangzhang/paper-typeahead-input#37]
Bonjour,

So I'm a bit surprised to see that `_suggestions` is defined in the _Private API_ instead of being public.
It would be really nice if it was public.

I'm using it as it is now - i.e `this.$.ptInput._suggestions.length` however accessing private properties makes me a tad uncomfortable 🌵 🌵 

Can we make it public?
### Use cases
- Display error/info messages if no suggestions are available
- It allows delegating the presentation of results into another element (perhaps an `<iron-list>`?) so suggestions can be displayed somewhere else. This could work by data-binding to this public `suggestions` prop

**Comment by cheonhyangzhang** [comment]
Can  you give a little more details about the second use case? Current behavior, paper-typeahead-input has a dropdown to show all the suggestions and that's the common behavior of a typeahead input. Why you think it's necessary to show the suggestions somewhere else? Isn't that duplicate information to user?

**Comment by nicholaswmin** [comment]
Def,

Perhaps someone might want to add buttons that perform an action for each suggestion. 

Without doing some hacky things to alter the DOM of `paper-typeahead-input` there's no way to go about it.

Publishing the `_suggestions` as public would allow building custom lists for the suggestions.
I'd take it that it's not a usual use case, but the cost of publishing the prop as public is minimal, no?

The prop can be set as `readOnly`, thus mitigating any risks of overwriting it outside of the component scope

> Isn't that duplicate information to user?

Hum, well that begs the question - how about also adding a `displaySuggestions` property to disable suggestions from the component internally, allowing to use `suggestions` to display _only_ somewhere else? 

I'm asking for too much here, I know, but it never hurts to ask :)

---

I can take this on and submit a PR if you agree with the above but you're short on time

**Comment by cheonhyangzhang** [comment]
Making _suggestions public is for sure easy change.

As you mentioned, making it readOnly would avoid data manipulation outside of the component.

I was trying to understand if that feature is really necessary. which is if when using paper-typeahead-input it needs to expose this piece of data.

Because I think it's always good to keep unnecessary data away from developers using paper-typeahead-input so that it doesn't bother them.

Based on your current explanation, I think it's fine to make it public. But let me think about it a little more time and also search for some existing typeahead js, e.g. twitter typeahead.js, etc. to see how they handle this.

**Comment by nicholaswmin** [comment]
> Based on your current explanation, I think it's fine to make it public. But let me think about it a little more time and also search for some existing typeahead js, e.g. twitter typeahead.js, etc. to see how they handle this.

Fair enough, let me know if I can be of any help

**Comment by cheonhyangzhang** [comment]
@nicholaswmin 
The changes are includes in v1.3.12. Added a getter function for _suggestions property.
https://github.com/cheonhyangzhang/paper-typeahead-input/releases/tag/v1.3.12

**Comment by nicholaswmin** [comment]
Thanks 🙇 

>  Added a getter function for _suggestions property.

But why not just make it a `readOnly`, public property instead of accessing it via a getter?

This would make it amenable to data binding outside of the element. This way I could observe changes to `suggestions` in a parent element

The way I see it, making it a `readOnly`, public prop results in:
- Less code since there's no need for the `getSuggestions()` method for the element itself
- More idiomatic to "Polymeric" concepts (data binding is the de-facto method for sharing data)
- Less code for using the property itself in a parent element - I can just observe the prop for changes

### A practical example:

```
<paper-typeahead-input suggestions="{{suggestions}}"></paper-typeahead-input>
<template is="dom-repeat" items="{{suggestions}}">
 // Suggestions delegated here
</template>
```

I don't think the `get/set` pattern should be used in any Polymer element. Polymer provides for private properties via that `readOnly` attribute thus mitigating any risks of that sort.

Thoughts?

**Comment by cheonhyangzhang** [comment]
I think by doing this
`suggestions:{
        type:Array,
        readOnly:true,
        value:[]
      },`
will cause 
`this.suggestions = [];`
`this.suggestions = matched`
to fail. Because cannot modify a readonly property.

Based on https://www.polymer-project.org/1.0/docs/devguide/properties,
readOnly    Type: boolean
If true, the property can't be set directly by assignment or data binding. See Read-only properties.

**Comment by nicholaswmin** [comment]
It can be done internally by using this format:

```
this._setSuggestions(matched);
```

Quoting from the same section you posted:

> When a property only "produces" data and never consumes data, this can be made explicit to avoid accidental changes from the host by setting the `readOnly` flag to true in the properties property definition. In order for the element to actually change the value of the property, it must use a private generated setter of the convention `_setProperty(value)`.

**Comment by cheonhyangzhang** [comment]
Changes are done on https://github.com/cheonhyangzhang/paper-typeahead-input/releases/tag/v1.3.13

I also delete the version v1.3.12 which is including the getter function.

**Comment by nicholaswmin** [comment]
Perfect, thanks a million 🙇 

Closing..

**Comment by cheonhyangzhang** [comment]
@nicholaswmin 
Thank you too.
