### ISSUE TITLE
Bug in remoteUrl handling

### ISSUE THREAD

**Issue by dasurid** [cheonhyangzhang/paper-typeahead-input#38]
In your `onreadystatechange` handler, you attempt to stuff the matched results into the suggestions property like so  (`ptinput.suggestions = matched`),  unfortunately suggestions is marked readonly, so in order for the remoteUrl suggestions menu to appear you should use the setter instead i.e. `ptinput._setSuggestions(matches)`

**Comment by cheonhyangzhang** [comment]
@dasurid 
Good call there, thanks for reporting.
This is a bug that's introduced by [v1.3.13](https://github.com/cheonhyangzhang/paper-typeahead-input/releases/tag/v1.3.13).

Will fix it asap

**Comment by cheonhyangzhang** [comment]
@dasurid 
This bug is fixed in [v1.3.14](https://github.com/cheonhyangzhang/paper-typeahead-input/releases/tag/v1.3.14)
