### ISSUE TITLE
Making the element hidden with `hidden` attribute

### ISSUE THREAD

**Issue by andrewspy** [cheonhyangzhang/paper-typeahead-input#40]
Is there a way to make the element `hidden`? i.e.

``` html
<paper-icon-button icon="search" on-tap="toggleTypeahead"></paper-icon-button>
<paper-typeahead-input id="typeahead" placeholder="Name" local-candidates="[[data]]" no-label-float on-pt-item-confirmed="itemConfirmed" hidden></paper-typeahead-input>
```

Thanks!

**Comment by cheonhyangzhang** [comment]
@andrewspy 
Do you want to hide the whole element? 
The input and the dropdown?

**Comment by andrewspy** [comment]
@cheonhyangzhang Yes, I intend to hide the whole element. The idea is to be able "expand" the `<paper-typeahead-input>` from 'hidden' stage when a `<paper-icon-button>` is clicked upon, and make it hidden again when `<paper-typeahead-input>` is `on-blur()`.

Currently, I am using the code below to hide it, but that's not an elegant way.

``` js
this.$.typeahead.style = 'display: none';
```

**Comment by cheonhyangzhang** [comment]
@andrewspy

I just tried the following code and it's working as expected. Clicking on switch is show/hide the paper-typeahead-input element.

`<p on-click="switch">Switch</p>
<paper-typeahead-input  local-candidates="{{states}}"  hidden="{{hidden}}">
</paper-typeahead-input>`

`app.hidden = true;
app.switch = function() {
app.hidden = !app.hidden;
};`

**Comment by andrewspy** [comment]
@cheonhyangzhang I can't test your javascript as I don't know how you define `app` (sorry, still a very beginner at DOM and javascript).

But I do know the following `hidden` attributes work with `<paper-input>` and not `<paper-typeahead-input>`:-

``` html
<paper-input label="Please enter" no-label-float hidden></paper-input>
<paper-typeahead-input local-candidates="[[data]]" hidden></paper-typeahead-input>
```

Also I saw some posting mentioning that `hidden` is special attribute which should be binding using `hidden$={{hidden}}` instead of `hidden={{hidden}}`. Not sure if that helps.

**Comment by cheonhyangzhang** [comment]
@andrewspy 
Ah sorry the code I posted above is not a standalone working code. It's just for demonstration purpose.
I tested in the paper-typeahead-input/demo/index.html page.
A little more context about it

```
<template is="dom-bind" id="app">
  <p on-click="switch">Switch</p>
  <paper-typeahead-input  local-candidates="{{states}}"  placeholder="US states" hidden="{{hidden}}">
<script>
  window.addEventListener('WebComponentsReady', function() {
    var app = document.querySelector('#app');
    app.hidden = true;
    app.switch = function() {
       app.hidden = !app.hidden;
    };
  });
</script>
</template>
```

I am not sure about `hidden$={{hidden}}` thing. Can you share the link of the post taking about it?

For me, `hidden={{hidden}}` is working as expected, but it might not be the best practice though.

**Comment by andrewspy** [comment]
@cheonhyangzhang Just tested your code, and it seems everything is working fine. I am gonna close this in investigate my own code.

Anyway, Here's document from Polymer - [Bind to a target attribute](https://www.polymer-project.org/1.0/docs/devguide/data-binding#attribute-binding). Not sure if that helps.

**Comment by cheonhyangzhang** [comment]
@andrewspy thanks for the doc.
Based on that doc, it's more efficient to use hidden$={{hidden}}.

Specifically, in your scenario, if using $ is working as you expected, you probably should use this attribute binding instead of property binding. because it is one way binding only from host to target.

**Comment by andrewspy** [comment]
Just wanted to add that you need to specify a CSS style inside a custom element to properly hide `<paper-typeahead-input>` inside a custom element, i.e:-

``` html
<style>
paper-typeahead-input[hidden] {
    display: none;
}
</style>
```

Took me a while to figure that out. Thanks anyway!

**Comment by cheonhyangzhang** [comment]
@andrewspy 
Really? That's a little weird to me. It doesn't make sense to have additional css to make it work. Did you try with using hidden={{hidden}} or hidden$={{hidden}}

**Comment by andrewspy** [comment]
Yes, I have tried both binding, and it somehow doesn't hide in Chrome (but it does hide in Firefix/Edge for some reason). Aanyway, here's the article I read (which I am not good with CSS myself) [Polymer and the [hidden] attribute](https://codingwithgerwin.blogspot.my/2016/04/polymer-and-hidden-attribute.html).

**Comment by cheonhyangzhang** [comment]
@andrewspy  got it. 
The article is really helpful.

So the hidden property works fine in my case probably because I am using the element in a very straightforward way. And in you case, you are using it with other elements. So you have to use a more specific css rule

```
<style>
paper-typeahead-input[hidden] {
    display: none;
}
</style>
```

To force the hidden property to work as expected.
