### ISSUE TITLE
focusing element with focus()

### ISSUE THREAD

**Issue by andrewspy** [cheonhyangzhang/paper-typeahead-input#41]
It seems I can't focus the element using the code below, i.e.

``` js
this.$.typeahead.focus();
```

**Comment by cheonhyangzhang** [comment]
@andrewspy  can you provide more context information?
where are you using this code?
what is the reason that you want to focus the input

**Comment by andrewspy** [comment]
@cheonhyangzhang As I mentioned in #40 , I intend to be able to `focus()` on the `<paper-input>` immediately when the `<paper-icon-button>` is clicked upon and `<paper-typeahead-input>` is "expanded" (i.e. hidden=false).

I also notice that the `autofocus` will only work the first time, and it will not autofocus on the '<paper-input>' subsequently when I set/reset the `.style` to/from `display: none`. Not sure if that's an bug.

Thanks!

**Comment by cheonhyangzhang** [comment]
Maybe we can add a focus function to paper-typeahead-input, which actually calls the focus call of paper-input element. 

As for the autofocus property, what's the expected behavior? I tried to find in the official Polymer doc, but the description didn't give too much details.

**Comment by andrewspy** [comment]
@cheonhyangzhang Yes, please add `focus()` function to call `<paper-input>`'s `focus()`.

As for the `autofocus` property, below is the extract from [W3School.com](http://www.w3schools.com/tags/att_input_autofocus.asp), which just mean the element will get autofocus first upon page loads. (Learn something new today :smiley:!)

> The autofocus attribute is a boolean attribute.
> When present, it specifies that an <input> element should automatically get focus when the page loads.

Hope that helps!

**Comment by cheonhyangzhang** [comment]
@andrewspy  Thanks for searching that. 
If it means element will be automatically get focus when page loads, what do u mean by "it will not autofocus on the  subsequently when I set/reset the .style to/from display: none"?  Isn't it supposed to get focus only when page loads?

**Comment by andrewspy** [comment]
@cheonhyangzhang I didn't know the meaning of `autofocus` in the first place, after understanding it, there is nothing wrong with the autofocus behavior, my bad.

The issue is only implementing the `focus()` function to `<papar-type-ahead>`. Thanks!

**Comment by andrewspy** [comment]
Reopen to request for `focus()` function.

**Comment by cheonhyangzhang** [comment]
@andrewspy  sure  no problem.  I added this issue to the next realease and will let you know when it's ready.

**Comment by cheonhyangzhang** [comment]
@andrewspy 
This feature has been included in [v1.3.5](https://github.com/cheonhyangzhang/paper-typeahead-input/releases/tag/v1.3.15).

**Comment by andrewspy** [comment]
@cheonhyangzhang I can confirmed the problem has been resolved. Closing the issue.

Thanks!
