### ISSUE TITLE
function to reset inputValue with resetValue()

### ISSUE THREAD

**Issue by andrewspy** [cheonhyangzhang/paper-typeahead-input#43]
If I wanna reset the inputValue in the middle of a typeahead with matched candidate, the `placeholder` value and the `candidate` text will be overlapped in the `<paper-input>`. Proposing to have a function `resetValue()` to reset the `inputValue` and clear the matched candidate at the same time. See below code when you "Switch" while there is a matched candidate:-

``` html
<!doctype html>
<html>
<head>
  <script src="./bower_components/webcomponentsjs/webcomponents-lite.js"></script>
  <link rel="import" href="./bower_components/paper-typeahead-input/paper-typeahead-input.html">
</head>
<body>
<template is="dom-bind" id="app">
  <p on-click="switch">Switch</p>
  <paper-typeahead-input id="typeahead" local-candidates="{{candidates}}" placeholder="Select Browser" hidden$="[[hidden]]"></paper-typeahead-input>
  <script>
    window.addEventListener('WebComponentsReady', function() {
      var app = document.querySelector('#app');

      app.candidates = [
        'Internet Explorer',
        'Firefox',
        'Chrome',
        'Opera',
        'Safari'
      ];

      app.hidden = false;

      app.switch = function() {
        app.$.typeahead.inputValue = ''; // Clear value
        app.hidden = !app.hidden;
      };
    });
  </script>
</template>
</body>
</html>

```

**Comment by cheonhyangzhang** [comment]
![evidence-bug-01](https://cloud.githubusercontent.com/assets/4094803/19444124/ca12d964-9454-11e6-89d1-c26a6aa6ce64.png)

Got your point. 
When I type "Int"  suggestions will show up and also typeahead will show up.
Then click on switch, it will show the overlapped text.

Hence need a function to reset the element to initial state.

This will be implemented in next release.
