### ISSUE TITLE
Using paper-material without dependency

### ISSUE THREAD

**Issue by Lithl** [cheonhyangzhang/paper-typeahead-input#45]
paper-typeahead-input version: 1.3.15
Polymer version: 1.8.1

[Line 15](https://github.com/cheonhyangzhang/paper-typeahead-input/blob/66291934622723d52a6a906ecfc34d82c13bcaef/paper-typeahead-input.html#L15) imports paper-material, but [bower.json](https://github.com/cheonhyangzhang/paper-typeahead-input/blob/66291934622723d52a6a906ecfc34d82c13bcaef/bower.json) doesn't list paper-material as a dependency.

As a result, including paper-typeahead-input as a dependency in another project (but not paper-material), running `bower install`, and then building the project with polymer-build throws an error:

    Error: ENOENT: no such file or directory, open '/path/to/my/project/bower_components/paper-material/paper-material.html'

Adding the paper-material dependency to the consuming project is a sufficient workaround, but it should be in paper-typeahead-input's dependency list.

**Comment by cheonhyangzhang** [comment]
Hi @Lithl 
This is going to be handled by #48
