### ISSUE TITLE
Support no-label-float

### ISSUE THREAD

**Issue by torsjonas** [cheonhyangzhang/paper-typeahead-input#5]
The element should propagate no-label-float attribute to the paper-input element.

**Comment by cheonhyangzhang** [comment]
@torsjonas 
Yep. I thinks this is a good call. 
no-label-float attribute will be helpful for customizing the input. 

I will include helpful properties of paper-input, including no-label-float to paper-typeahead-input.

**Comment by cheonhyangzhang** [comment]
no-label-float property has been added to paper-typeahead-input. together with other properties of paper-input that would make sense. 

https://github.com/cheonhyangzhang/paper-typeahead-input/blob/master/paper-typeahead-input.html#L173-L217

Is it fine that I close this issue?

**Comment by torsjonas** [comment]
Yes, updated and tested, works fine! Thank you.
