### ISSUE TITLE
Fire custom event when a value in the suggestion list has been selected by the user

### ISSUE THREAD

**Issue by torsjonas** [cheonhyangzhang/paper-typeahead-input#6]
The element should fire a custom-event (e.g. suggested-value-changed) when a value in the suggestion list has been selected by the user.

It is currently not possible to know the cause of the inputValue change from outside. It could change because the user is typing the first letters of a suggested value (but has not yet selected it), or it could change when the user pressed Enter key or clicks an item in the dropdown list of suggestions.

**Comment by cheonhyangzhang** [comment]
Hi @torsjonas 

Could you think of a practical case that we need to know if the changes are from user typing, or selected from the suggestions list?

**Comment by torsjonas** [comment]
In short, autosaving the selected value to another collection. It is a "nice to have" feature, but it removes a save-step for the user in my use case.

My overall use case is this:
The user wants to create a new collection of items by picking them from a typeahead element which has a list of suggestions (localCandidates). In this case the "items" are names of machines, and there are close to a thousand names in the suggestion list. I want to use a typeahead input since the user genarally knows what to search for, and will start typing the value. The names are very long, so the user will most probably stop typing after a few letters and instead select one of the suggestions, by tapping it or arrow down + enter key.

Since the created list must only contain values that match a value in the suggestion list exactly, I am not interested in any events from the typeahead element other than when a suggestion value has been selected as the inputValue. When this event triggers, I can save the value to the collection that the user is creating.

My current approach is that the user must click a save button after selecting a suggestion (plus, I must validate that the inputValue is in fact in the suggestion list or show an error to the user).

If there was an event when a suggestion has been selected I could remove the save button, and I could skip validation that the value is in the suggestion list.

**Comment by cheonhyangzhang** [comment]
Thanks for the detailed explanation. 
I think you are making a great point. 
Having a custom event is a good idea. 
I will throw some thoughts on it and come up with a solution for that.

**Comment by torsjonas** [comment]
Great! As further input, these could be some conditions that would trigger the event:
1. When a suggestion has been selected by tapping it.
2. When a suggestion has been selected by arrow keys + Enter.
3. When a suggestion has been entered by manually by typing each letter and then pressing Enter (this might technically be the same as 2 above?).

**Comment by cheonhyangzhang** [comment]
Custom event is added to paper-typeahead element in release 1.2.0. Now it supports two events, 
pt-item-select and pt-item-changed, inspired by iron-select and items-changed event of paper-menu. 

The one you are looking for is pt-item-changed, it will be fired either by clicking on an element in the suggestion list or arrow keys + Enter. 

As for the 3rd case you mentioned, I don't think that should be the same event as 1st and 2nd.

**Comment by torsjonas** [comment]
Thanks for the update!

It appears that the pt-item-changed event is fired too many times for my purpose. It fires whenever the list of suggestions change. When I type a few characters matching several suggestions, shrinking the list of suggestions as I type more characters, shrinking the suggestion list, this fires the pt-item-changed event every time the list shrinks. It does also fire when I click on one of the suggestions or arrow keys + Enter, but because of the many other events as I explained above this is not useful in my use case.

Could a custom event be fired only on lines 308 and 353 of paper-typeahead-input.html (only when a suggestion has been selected)?

**Comment by cheonhyangzhang** [comment]
Oh Sorry for that. Will fix it. Had a wrong understanding of the items-changed event of paper-menu element.

**Comment by cheonhyangzhang** [comment]
Your are right, custom event being fired on 308 and 353 is a great idea. I have made those changes in the latest commit, tagged as v1.2.2.

**Comment by torsjonas** [comment]
Tried it and it works great, thanks!

**Comment by cheonhyangzhang** [comment]
Okay. Cool. Glad to hear that.
