### ISSUE TITLE
Support debounced web request to remoteUrl

### ISSUE THREAD

**Issue by torsjonas** [cheonhyangzhang/paper-typeahead-input#9]
The paper-typeahead-input supports a remoteUrl and combines the fetched results with the suggestion list. This is a great feature!

However, I have been avoiding it because I do not want to hammer the server by sending a new web request every time the user types a new character. Typically, the user  will type several characters, maybe deleting a few and typing more to spell the beginning of a longer word or sentence. Every one of those changes sends a web request. By making the web request function call debounced, lets say 250 ms, the number of unnecessary web requests will be be reduced by a lot.

So what I do right now is to externally debounce a web request when the bind-value-changed event fires from the paper-input, and I rebind the pt localCandidates list with the result. I then call the private function _search (which i should not do...) to display the new suggestions from localCandidates. It would be nice if paper-typeahead-input would support a debounced web request to remoteUrl.

This would not add much extra complexity to the code, it would simply be the same function call, only wrapped with a debouncer. The debounce wait time could be a new property 'debounceMs' (type: Number) that defaults to undefined, which will cause the function to be called as soon as possible so the behaviour will remain the same as now.

``` javascript
    if (typeof(this.remoteUrl) != 'undefined'){
        var self = this;
        this.debounce('remoteSearch', function() {
           var url = self.remoteUrl.replace("%QUERY", term);
           ...
           xmlhttp.send();
         }, this.debounceMs);
    }
```

It would probably make sense to cancel the debounced function call when the user confirms a suggestion (has found what he/she was searching for), like so:

``` javascript
   this.cancelDebouncer('remoteSearch');
```

**Comment by cheonhyangzhang** [comment]
This is an interesting point. So in summary, you are suggesting:
add some customizable delay to the search for remoteUrl
instead of firing the http request after typing every single character.
Is that correct?

Say, if set up the delay wait time to be 1 second, 
the user type "a", then a search to remoteUrl is set up by debounce, and will fire up after 1 second,
but user types fast and another "b" comes, so a new search is set up with search term "ab" and scheduled to be fired up 1 second later. 

The first search hasn't been fired and it will be canceled automatically ( I guess, I am not very familiar with the debounce function. [Polymer doc](https://www.polymer-project.org/1.0/docs/devguide/utility-functions.html) said: Call debounce to collapse multiple requests for a named task into one invocation, which is made after the wait time has elapsed with no new request. ). 

So without the delay feature, 2 calls will be made, and with only 1 call will be made.

Am I right about the concept here?

**Comment by torsjonas** [comment]
That's exactly right. Debouncing the web request is a simple way to reduce the burden on the remote web server in this case. There is really not much point in sending many web requests as long as the user keeps typing quickly. I find that a wait time of 250ms or maybe a bit lower works pretty well for me.

**Comment by cheonhyangzhang** [comment]
This debounced feature has been implemented in release 1.3.1. 

I am not sure about the cancelDebouncer. When user begin to select, either by mouse or by keyboard, they already stopped typing, no more request should be in the queue at the moment an item from suggestion is confirmed(if the wait time is set up properly). 
.

**Comment by torsjonas** [comment]
Perfect, I tested it and it works well. I can now happily throw away a bunch of code I wrote that did the same thing externally. Thank you very much for the quick update.

Just for completeness, would it be possible to also add a Boolean property with notify: true that is true when there is an async web request going on? That way I can show a paper-spinner on my page when there is an async web request that is active in the paper-typeahead-input.

**Comment by cheonhyangzhang** [comment]
Well, adding a boolean property will solve the problem but I am not sure if that is intuitive enough. 
A boolean property called remoteUrlSearching? to indicate if a request is on the way?

How about firing custom event when request is scheduled and request is finished? 

Or both?

**Comment by torsjonas** [comment]
Yes an event would work. I could use a handler for that event like so:

``` javascript
<paper-typeahead-input on-remote-url-searching-changed="handleUrlSearchingChanged">
</paper-typeahead-input>

handleUrlSearchingChanged: function(remoteUrlSearching) {
   this.$.spinner.active = remoteUrlSearching;
}
```

**Comment by cheonhyangzhang** [comment]
Yep. I would say both of the two approaches would work. Not sure which one is better, what's your thoughts?

**Comment by torsjonas** [comment]
The event, that way I can just copy paste the suggested event handler from this issue thread ;-)

No but seriously, I guess its just a matter of taste and consistency in how your element notifies changes for stuff. A benefit of a custom event is that it bubbles upward, parent elements high up in the hierarchy can listen to the same event. With a property, there would have to be a chain of property propagation.

**Comment by cheonhyangzhang** [comment]
Think it might be a good idea to support both. Done in 1.3.2. Added property remoteUrlSearching and custom event pt-remote-searching-start and pt-remote-searching-end.

**Comment by torsjonas** [comment]
OK!
I noticed a mistake, on this line

``` javascript
this.fire('pt-remote-searching-end',pt_element);
```

fire is not defined. You need a var self = this or bind the function to this.

**Comment by raghav135** [comment]
+1 to torsjonas.

var self = this , and self.fire required for line 449.

**Comment by cheonhyangzhang** [comment]
Good call. Fixed.

**Comment by cheonhyangzhang** [comment]
Hi Guys, @torsjonas  @raghav135 

I think this issue is resolved and I am going to close this issue.

**Comment by raghav135** [comment]
I agree, this is resolved. I have tested the same.
Cheers.
